# Generated by Django 4.2.6 on 2023-10-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время рассылки')),
                ('period', models.CharField(blank=True, choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=20, null=True, verbose_name='периодичность')),
                ('status', models.CharField(blank=True, choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], max_length=20, null=True, verbose_name='статус рассылки')),
                ('theme', models.CharField(max_length=150, verbose_name='тема')),
                ('mailing_text', models.TextField(blank=True, null=True, verbose_name='текст письма')),
                ('customer', models.ManyToManyField(max_length=150, to='mailing.customer', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('last_try_status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='ok', max_length=20)),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('customer', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='mailing.customer', verbose_name='клиент')),
                ('mailing', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
